version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
      #golang: latest
  pre_build:
    commands:
      - echo Pre_build started on `date`
      - go version
      - echo `go env | grep GOMODCACHE`
      - sam --version
      # go mod download
      - cd appbase && go mod download
      - cd ../app && go mod download
      - cd ..

  build:
    commands:      
      - echo Build started on `date`
      - make build_linux
      - echo Unit Test started on `date`
      - make unit_test
      #- echo Integration Test started on `date`      
      #- make integration_test
cache:
  paths:    
    - '/go/pkg/**/*'     