AWSTemplateFormatVersion: 2010-09-09
Description: AppConfig Template for CloudFormation Demo. Depends on cfn-iam.yaml, cfn-rds.yaml.
#Metadata: 
Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  ApplicationName:
    Type: String
    Default: todo-app
  Stage:
    Type: String
    AllowedValues:
      - Prod
      - Staging
      - Dev      
    Default: Prod 
  HostedConfigurationProfileName:
    Type: String
    Default: config
  SecretsManagerConfigurationProfileName:
    Type: String
    Default: sm-config

#Mappings: 

#Conditions: 

Resources: 
  AppConfigApplication:
    Type: AWS::AppConfig::Application
    Properties:    
      Name: !Ref ApplicationName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-AppConfigApplication

  AppConfigEnv:
    Type: AWS::AppConfig::Environment
    Properties:
      ApplicationId: !Ref AppConfigApplication
      Name: !Ref Stage
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-AppConfigEnv

  AppConfigHostedProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigApplication
      LocationUri: hosted
      Name: !Ref HostedConfigurationProfileName
      Type: AWS.Freeform
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-AppConfigProfile

  AppConfigSecretsManagerProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigApplication
      LocationUri: !Sub secretsmanager://${StackPrefix}-RDS-Secrets
      RetrievalRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigRoleArn
      Name: !Ref SecretsManagerConfigurationProfileName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-AppConfigSecretsManagerProfile      

  AppConfigDeploymentStrategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      Name: !Sub ${ApplicationName}-DeploymentStrategy
#     DeploymentDurationInMinutes: 3        
#      FinalBakeTimeInMinutes: 4
      DeploymentDurationInMinutes: 1
      FinalBakeTimeInMinutes: 1
#      GrowthFactor: 50
      GrowthFactor: 10
      GrowthType: LINEAR
      ReplicateTo: NONE
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-DeploymentStrategy

Outputs:
  AppConfigApplicationID:
    Description: AppConfig Application ID
    Value: !Ref AppConfigApplication
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigApplicationID
  AppConfigEnvID:
    Description: AppConfig Environment ID
    Value: !Ref AppConfigEnv
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigEnvID
  AppConfigDeploymentStrategyID:
    Description: AppConfig DeploymentStrategy ID
    Value: !Ref AppConfigDeploymentStrategy
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigDeploymentStrategyID
  AppConfigHostedProfileID:
    Description: AppConfig Hosted ConfigurationProfile ID
    Value: !Ref AppConfigHostedProfile
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigHostedProfileID
  AppConfigHostedProfileLambdaExtensionURL:  
    Description: Hosted AppConfig Lambda Extension Endpoint URL
    Value: !Sub http://localhost:2772/applications/${ApplicationName}/environments/${Stage}/configurations/${HostedConfigurationProfileName}    
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigHostedProfileLambdaExtension${Stage}URL
  AppConfigSecretsManagerProfileID:
    Description: AppConfig SecretsManager ConfigurationProfile ID
    Value: !Ref AppConfigSecretsManagerProfile
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigSecretsManagerProfileID
  SecretsManagerAppConfigLambdaExtensionURL:  
    Description: Secrets Manager AppConfig Lambda Extension Endpoint URL
    Value: !Sub http://localhost:2772/applications/${ApplicationName}/environments/${Stage}/configurations/${SecretsManagerConfigurationProfileName} 
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigSMProfileLambdaExtension${Stage}URL
  AppConfigLambdaExtensionPath:
    Description: AppConfig Lambda Extension Endpoint Path
    Value: 
      Fn::Join:
        - ","
        - - !Sub /applications/${ApplicationName}/environments/${Stage}/configurations/${HostedConfigurationProfileName}
          - !Sub /applications/${ApplicationName}/environments/${Stage}/configurations/${SecretsManagerConfigurationProfileName}
    Export: 
      Name: !Sub ${StackPrefix}-AppConfigLambdaExtension${Stage}Path