AWSTemplateFormatVersion: 2010-09-09
Description: AppConfig Deployment Template for CloudFormation Demo. Depends on cfn-appconfig.yaml, cfn-rds.yaml, cfn-s3.yaml, template.yaml.
#Metadata: 
Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  Stage:
    Type: String
    AllowedValues:
      - Prod
      - Staging
      - Dev
    Default: Prod    
#Mappings: 

#Conditions: 

Resources: 
  AppConfigHostedConfigurationVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigApplicationID
      ConfigurationProfileId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigHostedProfileID
      ContentType: text/plain
      Content:
        Fn::Join:
          - ""
          - - |
              hoge_name: foo
              fuga_name: gaa
              TODO_TABLE_NAME: todo
              TEMP_TABLE_NAME: temp
              #USERS_TABLE_NAME: users
              QUEUE_MESSAGE_TABLE_NAME: queue_message
              QUEUE_MESSAGE_TABLE_TTL_HOUR: 96
              GIN_DEBUG: true
              DYNAMODB_RETURN_CONSUMED_CAPACITY: true
              #AWSSDK_CLIENT_LOG_MODE: LogSigning,LogRetries,LogRequestWithBody,LogResponseWithBody,LogDeprecatedUsage,LogRequestEventMessage,LogResponseEventMessage
              RDB_SSL_MODE: require                           
            - "\nRDB_ENDPOINT: "
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSProxyEndpoint
            - "\nRDB_PORT: "
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
            - "\nRDB_DB_NAME: "
            - Fn::ImportValue: !Sub ${StackPrefix}-RDSDBName     
            - "\nUSERS_API_BASE_URL: "
            - Fn::ImportValue: !Sub ${StackPrefix}-UsersAPIBaseURL-${Stage}
            - "\nTODO_API_BASE_URL: "
            - Fn::ImportValue: !Sub ${StackPrefix}-TodoAPIBaseURL-${Stage}
            - "\nS3_BUCKET_NAME: "            
            - Fn::ImportValue: !Sub ${StackPrefix}-S3BucketName

  AppConfigHostedProfileDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigApplicationID
      EnvironmentId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigEnvID
      ConfigurationProfileId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigHostedProfileID
      ConfigurationVersion: !Ref AppConfigHostedConfigurationVersion
#      DeploymentStrategyId: AppConfig.AllAtOnce
#      DeploymentStrategyId: AppConfig.Linear50PercentEvery30Seconds
#      DeploymentStrategyId: AppConfig.Linear20PercentEvery6Minutes
      DeploymentStrategyId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigDeploymentStrategyID
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-AppConfigHostedProfileDeployment