AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB Template for CloudFormation Demo. Depends on .
#Metadata: 

Parameters: 
#  UsersTableName:
#    Type: String
#    Default: users    
  TodoTableName:
    Type: String
    Default: todo

#Mappings: 

#Conditions: 

Resources: 
# DynamoDB
# User table on DynamoDB is not used now
#  UsersTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: !Ref UsersTableName
#      KeySchema:
#        - AttributeName: user_id
#          KeyType:  HASH
#      AttributeDefinitions:
#        - AttributeName: user_id
#          AttributeType: S
#      BillingMode: PAY_PER_REQUEST   
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TodoTableName
      KeySchema:
        - AttributeName: todo_id
          KeyType:  HASH
      AttributeDefinitions:
        - AttributeName: todo_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
# TODO: temp Table
# TODO: queue_message Table


#Outputs: