AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager Template for CloudFormation Demo. 
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  AuroraDBUsername:
    NoEcho: 'true'
    Description: MasterUsername for Aurora PostgreSQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DocDBUsername:
    NoEcho: 'true'
    Description: MasterUsername for DocumentDB database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

#Mappings: 
#Conditions: 

Resources: 
# Secrets Manager
# https://docs.aws.amazon.com/ja_jp/secretsmanager/latest/userguide/reference_secret_json_structure.html#reference_secret_json_structure_rds
  RDSSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackPrefix}-RDS-Secrets
      Description: RDS Aurora Secrets
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${AuroraDBUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"      
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-RDS-SecretsManager
# Secrets Manager for DocumentDB
# https://docs.aws.amazon.com/ja_jp/secretsmanager/latest/userguide/reference_secret_json_structure.html#reference_secret_json_structure_docdb
  DocumentDBSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackPrefix}-DocDB-Secrets
      Description: DocumentDB Secrets
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DocDBUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-DocDB-SecretsManager
Outputs:
  RDSSecretsManagerName:
    Description: RDS Secrets Manager Name
    Value: !Sub ${StackPrefix}-RDS-Secrets
  DocumentDBSecretsManagerName:
    Description: DocumentDB Secrets Manager Name
    Value: !Sub ${StackPrefix}-DocDB-Secrets
  RDSSecretsManagerArn:
    Description: RDS Secrets Manager Arn
    Value: !Ref RDSSecretsManager
    Export: 
      Name: !Sub ${StackPrefix}-RDSSecretsManagerArn
  DocumentDBSecretsManagerArn:
    Description: DocumentDB Secrets Manager Arn
    Value: !Ref DocumentDBSecretsManager 
    Export: 
      Name: !Sub ${StackPrefix}-DocDBSecretsManagerArn      