AWSTemplateFormatVersion: 2010-09-09
Description: IAM Template for CloudFormation Demo. 
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo 
#Mappings: 

#Conditions: 

Resources:
  #IAM Profile and Role for Bastion
  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: BastionRole      
  BastionRole:  
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com  
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BastionRole        

Outputs:
  BastionInstanceProfile:
      Description: BastionInstanceProfile Logical ID
      Value: !Ref BastionInstanceProfile
      Export: 
        Name: !Sub ${StackPrefix}-BastionInstanceProfile