AWSTemplateFormatVersion: 2010-09-09
Description: IAM Template for CloudFormation Demo. 
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo 
#Mappings: 

#Conditions: 

Resources:
  #IAM Profile and Role for Bastion
  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: BastionRole      
  BastionRole:  
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com  
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-BastionRole      
  #IAM Role for RDS Proxy
  RDSProxyRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - sts:AssumeRole 
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-RDSProxyRole
  RDSProxyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${StackPrefix}-RDSProxyPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue            
            Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
          - Effect: Allow
            Action:
              - kms:Decrypt            
            Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*
            Condition:
              StringEquals:
                kms:ViaService: !Sub secretsmanager.${AWS::Region}.amazonaws.com
      Roles:
        - !Ref RDSProxyRole
Outputs:
  BastionInstanceProfile:
    Description: BastionInstanceProfile Logical ID
    Value: !Ref BastionInstanceProfile
    Export: 
      Name: !Sub ${StackPrefix}-BastionInstanceProfile
  RDSProxyRoleArn:
    Description: Information about the value
    Value: !GetAtt RDSProxyRole.Arn
    Export: 
      Name: !Sub ${StackPrefix}-RDSProxyRoleArn