AWSTemplateFormatVersion: 2010-09-09
Description: AppConfig Deployment Template for CloudFormation Demo. Depends on cfn-appconfig.yaml.
#Metadata: 
Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo

#Mappings: 

#Conditions: 

Resources: 
  AppConfigHostedConfigurationVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigApplicationID
      ConfigurationProfileId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigProfileID
      ContentType: text/plain
      Content: |
        hoge_name: foo
        fuga_name: gaa
        TODO_TABLE_NAME: todo
        TEMP_TABLE_NAME: temp
        QUEUE_MESSAGE_TABLE_NAME: queue_message
        QUEUE_MESSAGE_TABLE_TTL_HOUR: 96
        GIN_DEBUG: true                
#        LOG_LEVEL: DEBUG
#        USERS_TABLE_NAME: users
  AppConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigApplicationID
      EnvironmentId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigEnvID
      ConfigurationProfileId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigProfileID
      ConfigurationVersion: !Ref AppConfigHostedConfigurationVersion
#      DeploymentStrategyId: AppConfig.AllAtOnce
#      DeploymentStrategyId: AppConfig.Linear50PercentEvery30Seconds
#      DeploymentStrategyId: AppConfig.Linear20PercentEvery6Minutes
      DeploymentStrategyId:
        Fn::ImportValue: !Sub ${StackPrefix}-AppConfigDeploymentStrategyID
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Deployment
