AWSTemplateFormatVersion: 2010-09-09
Description:  SQS Template for CloudFormation Demo.
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo 
  StandardSourceQueueName:
    Description: Standard Source Queue Name
    Type: String
    Default: SampleQueue
  DeadLetterQueueName:
    Description: Dead Letter Queue Name
    Type: String
    Default: SampleDLQueue
  FifoQueueName:
    Description: FIFO Queue Name
    Type: String
    Default: SampleFIFOQueue.fifo

#Mappings: 

#Conditions: 

Resources: 
  StandardSourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref StandardSourceQueueName
      DelaySeconds: 5
      RedrivePolicy:       
        deadLetterTargetArn:
          !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3          
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 30
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Queue
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DeadLetterQueueName
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-DLQueue   
  FifoQueue:  
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref FifoQueueName
      DelaySeconds: 5      
      ReceiveMessageWaitTimeSeconds: 20      
      VisibilityTimeout: 30
      FifoQueue:  true
      ContentBasedDeduplication: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-FIFOQueue
Outputs:
  StandardSourceQueueName:
    Description: Standard Source Queue Name
    Value: !Ref StandardSourceQueueName
    Export:
      Name: !Sub ${StackPrefix}-SQSQueueName
  StandardSourceQueueURL: 
    Description: URL of Standard Source Queue
    Value: !Ref StandardSourceQueue
  StandardSourceQueueARN: 
    Description: ARN of Standard Source Queue
    Value: !GetAtt StandardSourceQueue.Arn
    Export:
      Name: !Sub ${StackPrefix}-SQSQueueArn
  DeadLetterQueueURL: 
    Description: URL of DeadLetter Queue
    Value: !Ref DeadLetterQueue
  DeadLetterQueueARN: 
    Description: ARN of DeadLetter Queue
    Value: !GetAtt DeadLetterQueue.Arn    
  FifoQueueName:
    Description: FIFO Queue Name
    Value: !Ref FifoQueueName
    Export:
      Name: !Sub ${StackPrefix}-SQSFifoQueueName
  FifoQueueURL: 
    Description: URL of Standard Source Queue
    Value: !Ref FifoQueue
  FifoQueueARN: 
    Description: ARN of Standard Source Queue
    Value: !GetAtt FifoQueue.Arn
    Export:
      Name: !Sub ${StackPrefix}-SQSFifoQueueArn    