hoge_name: "fuga-localtest"
TODO_TABLE_NAME: "todo"
TEMP_TABLE_NAME: "temp"
QUEUE_MESSAGE_TABLE_NAME: "queue_message"
#USERS_TABLE_NAME: "users"
RDB_USER: "postgres"
RDB_PASSWORD: "password"
RDB_ENDPOINT: "host.docker.internal"
RDB_PORT: "5432"
RDB_DB_NAME: "testdb"
RDB_SSL_MODE: "disable"
TODO_API_BASE_URL: "http://host.docker.internal:3000"
USERS_API_BASE_URL: "http://host.docker.internal:3000"
DYNAMODB_LOCAL_ENDPOINT: "http://host.docker.internal:8000"
SQS_LOCAL_ENDPOINT: "http://host.docker.internal:9324"
#LOG_LEVEL: INFO