hoge_name: "fuga-local"
TODO_TABLE_NAME: "todo"
TEMP_TABLE_NAME: "temp"
QUEUE_MESSAGE_TABLE_NAME: "queue_message"
QUEUE_MESSAGE_TABLE_TTL_HOUR: "96"
#USERS_TABLE_NAME: "users"
DYNAMODB_LOCAL_ENDPOINT: "http://host.docker.internal:8000"
SQS_LOCAL_ENDPOINT: "http://host.docker.internal:9324"
#LOG_LEVEL: INFO