version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001  
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
